# 데이터 분석
## 가. 개념 : 데이터를 수집, 정제, 해석하여 숨겨진 패턴과 유용한 정보(인사이트)를 발견하고, 이를 바탕으로 미래의 발생 가능한 상황을 예측하고 최적의 의사결정을 내리는 일련의 과정
## 나. 분석과정
### 1. 데이터 수집 : 분석에 필요한 데이터 확보
### 2. 데이터 전처리(preprocessing) : 데이터를 분석에 적합한 형태로 만들어서 신뢰도를 높이는 작업
### 3. 데이터 탐색 : 그래프나 통계적인 방법을 이용, 데이터의 특징과 패턴을 파악
### 4. 모델링 : 수집, 정제된 데이터를 기반으로 수학적, 통계적인 방법을 사용하여 데이터 간의 관계를 파악하고, 새로운 데이터에 대해서 결과를 예측하거나 설명할 수 있는 규칙(model)을 만드는 과정
### 5. 분석 모델 평가

# numpy(넘파이)
## 가. 정의 : 수학적 계산을 위한 파이썬 라이브러리
## 나. 자료형 : 다차원 배열(ndarray) ↔ 파이썬 리스트
### 1. python list 자료형과 numpy 다차원 배열 자료 구조 비교
    * python list
        * 존재 목적 / 장점
        다양한 자료형의 데이터 혼합 저장:
        정수, 실수, 문자열, 심지어 다른 리스트 등 어떤 종류의 데이터든 하나의 리스트 안에 자유롭게 담을 수 있음
        * 요소별 수학 연산 : 불가능
    * numpy 다차원 배열
        * 존재 목적 / 장점
            * 단일 종류의 숫자 데이터 중심
            * 대규모 수치 데이터를 묶어서 빠르고 효율적으로 처리
        * 요소별 수학 연산 : 가능(최대 장점)
### 2. 주요 특징
#### 가) 압도적인 연산 성능과 효율성: 대량의 숫자 데이터를 매우 빠르게 처리한 수 있음
#### 나) 풍부한 수학적 연산 기능 제공: 사칙연산, 통계(평균, 합계, 표준편차), 선형 대수, 푸리에 변한 등 데이터 분석에 필수적인 다양한 수학 함수들을 제공

In [2]:
# 사용하기 : 라이브러리 임포트
# numpy 라이브러리를 import하고 앞으로 np라는 이름으로 부른다.
import numpy as np

In [ ]:
# np.array(data) 함수
## data = python 리스트 또는 튜플, python 리스트(튜플)로부터 생성
list_data = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
print(list_data, arr, sep = "\n")

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
# np.array 연산
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr = arr * 3
print(arr)
arr = arr + 1
print(arr)

[1 2 3 4 5]
[ 3  6  9 12 15]
[ 4  7 10 13 16]


In [ ]:
# np.array 통계
arr = np.array([1, 2, 3, 4, 5])
print(arr.mean()) # 평균값
print(np.median(arr)) # 중앙값(중위수)
print(arr.std()) # 표준편차
print(arr.var()) # 분산
print(np.percentile(arr, 50)) # 백분위수 (0~100)
print(np.quantile(arr, 0.5)) # 분위수 (0 ~ 1)

3.0
3.0
1.4142135623730951
2.0
3.0
3.0


In [6]:
# array 인덱싱
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0, 2])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
3


In [8]:
# 1차원 array 슬라이싱
## 배열[start 인덱스 : stop 인덱스]
### start 인덱스부터 stop 인덱스 바로 전까지 값 추출 (start <= x < stop)
arr = np.array(range(10))
print(arr)
arr1 = arr[3:8]
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]


In [9]:
# 2차원 array 슬라이싱
## 배열[행 start 인덱스 : 행 stop 인덱스, 열 start 인덱스 : 열 stop 인덱스
arr = np.array([range(0, 10), range(10, 20), range(20, 30), range(30, 40)])
print(arr)
arr1 = arr[:, 4:9]
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[ 4  5  6  7  8]
 [14 15 16 17 18]
 [24 25 26 27 28]
 [34 35 36 37 38]]
